services:
  caddy:
    build:
      target: prod
    env_file: ./caddy/.env.prod

  postgres_db: !reset null

  api:
    image: ghcr.io/kapobajza/zdnevnik_api:prod
    depends_on:
      postgres_db: !reset null
    env_file: ./apps/api/.env.prod
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
    labels:
      - "promtail=true"

  web:
    image: ghcr.io/kapobajza/zdnevnik_web:prod
    env_file: ./apps/sveltastic/.env.prod
    labels:
      - "promtail=true"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first

volumes:
  postgres_data: !reset null
