name: zdnevnik

services:
  postgres_db:
    image: postgres:15
    restart: always
    env_file: ./db/.env.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 20s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "promtail=true"
    ports:
      - 5435:5432

volumes:
  postgres_data:
