services:
  caddy:
    build:
      target: prod
    env_file: ./caddy/.env.prod
  postgres_db: !reset null
  api:
    build:
      target: prod
    depends_on:
      postgres_db: !reset null
    env_file: ./apps/api/.env.prod

volumes:
  postgres_data: !reset null
