// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ba'

export type Locales =
	| 'ba'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​r​i​j​a​v​i​ ​s​e​ ​i​ ​o​d​g​o​v​o​r​i​ ​n​a​ ​p​i​t​a​n​j​e​ ​<​s​p​a​n​ ​c​l​a​s​s​=​"​z​d​-​t​e​x​t​-​p​r​i​m​a​r​y​"​>​"​K​o​j​i​ ​s​i​ ​t​i​ ​b​r​o​j​"​<​/​s​p​a​n​>​?
	 */
	login_title: string
	/**
	 * P​o​g​r​e​š​n​o​ ​k​o​r​i​s​n​i​č​k​o​ ​i​m​e​ ​i​l​i​ ​l​o​z​i​n​k​a
	 */
	login_error_invalid_credentials: string
	/**
	 * P​r​i​j​a​v​a
	 */
	login_submit_button: string
	/**
	 * K​o​r​i​s​n​i​č​k​o​ ​i​m​e
	 */
	login_username_placeholder: string
	/**
	 * L​o​z​i​n​k​a
	 */
	login_password_placeholder: string
	/**
	 * {​f​i​e​l​d​}​ ​j​e​ ​{​g​e​n​d​e​r​?​|​{​m​:​ ​o​b​a​v​e​z​a​n​,​ ​f​:​ ​o​b​a​v​e​z​n​a​,​ ​*​:​ ​o​b​a​v​e​z​n​o​}​}
	 * @param {string} field
	 * @param {'m' | 'f' | string} [gender]
	 */
	validation_field_required: RequiredParams<'field' | `gender?|{m:${string}, f:${string}, *:${string}}`> | RequiredParams<'field'>
	/**
	 * {​f​i​e​l​d​}​ ​j​e​ ​{​g​e​n​d​e​r​?​|​{​m​:​ ​p​r​e​k​r​a​t​a​k​,​ ​f​:​ ​p​r​e​k​r​a​t​k​a​,​ ​*​:​ ​p​r​e​k​r​a​t​k​o​}​}
	 * @param {string} field
	 * @param {'m' | 'f' | string} [gender]
	 */
	validation_field_too_short: RequiredParams<'field' | `gender?|{m:${string}, f:${string}, *:${string}}`> | RequiredParams<'field'>
	/**
	 * G​r​e​š​k​a
	 */
	error_title: string
	/**
	 * D​o​g​o​d​i​l​a​ ​s​e​ ​n​e​p​o​z​n​a​t​a​ ​g​r​e​š​k​a
	 */
	error_unknown: string
}

export type TranslationFunctions = {
	/**
	 * Prijavi se i odgovori na pitanje <span class="zd-text-primary">"Koji si ti broj"</span>?
	 */
	login_title: () => LocalizedString
	/**
	 * Pogrešno korisničko ime ili lozinka
	 */
	login_error_invalid_credentials: () => LocalizedString
	/**
	 * Prijava
	 */
	login_submit_button: () => LocalizedString
	/**
	 * Korisničko ime
	 */
	login_username_placeholder: () => LocalizedString
	/**
	 * Lozinka
	 */
	login_password_placeholder: () => LocalizedString
	/**
	 * {field} je {gender?|{m: obavezan, f: obavezna, *: obavezno}}
	 */
	validation_field_required: (arg: { field: string, gender?: 'm' | 'f' | string }) => LocalizedString
	/**
	 * {field} je {gender?|{m: prekratak, f: prekratka, *: prekratko}}
	 */
	validation_field_too_short: (arg: { field: string, gender?: 'm' | 'f' | string }) => LocalizedString
	/**
	 * Greška
	 */
	error_title: () => LocalizedString
	/**
	 * Dogodila se nepoznata greška
	 */
	error_unknown: () => LocalizedString
}

export type Formatters = {}
