name: Deploy to VPS

description: 'Deploys the built docker image to VPS'

inputs:
  service:
    description: 'Service name'
    required: true
  vps_host:
    description: 'VPS host'
    required: true
  vps_username:
    description: 'VPS username'
    required: true
  vps_key:
    description: 'VPS key'
    required: true
  vps_port:
    description: 'VPS port'
    required: true
  vps_folder:
    description: 'VPS folder'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.vps_host }}
        username: ${{ inputs.vps_username }}
        key: ${{ inputs.vps_key }}
        port: ${{ inputs.vps_port }}
        script: |
          cd ~/${{ inputs.vps_folder }}
          ./scripts/deploy.sh ${{ inputs.service }}
  
