name: Build and push docker image

description: 'Builds a docker image and pushes it to the GHCR registry'

inputs:
  service:
    description: 'Service name'
    required: true
  dockerfile_dir:
    description: 'Directory containing Dockerfile'
    required: true
  gh_token:
    description: 'A Github PAT'
    required: true
  gh_cr_username:
    description: 'A Github CR username'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.gh_cr_username }}
        password: ${{ inputs.gh_token }}
    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/kapobajza/zdnevnik_${{ inputs.service }}:prod
        file: ${{ inputs.dockerfile_dir }}/Dockerfile
        target: prod
        platforms: linux/amd64
        cache-from: type=registry,ref=ghcr.io/kapobajza/zdnevnik_${{ inputs.service }}:prod
        cache-to: type=inline
  
