services:
  promtail:
    env_file: .env.prod
    environment:
      - LOKI_URL=http://loki:3100

  grafana:
    env_file: .env.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.logging.rule=Host(`logging.zdnevnik.com`)"
      - "traefik.http.routers.logging.entrypoints=websecure"
      - "traefik.http.services.grafana.loadbalancer.server.port=3200"

  reverse_proxy:
    image: traefik:v3.1
    restart: unless-stopped
    command:
      # HTTP to HTTPS global redirection
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      # Dynamic configuration file for certs
      - "--providers.file.filename=/etc/traefik/dynamic/certs-config.yaml"
      # Docker configuration
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../traefik/certs-config.yaml:/etc/traefik/dynamic/certs-config.yaml:ro
      - ../traefik/certs:/etc/certs:ro

  postgres:
    image: postgres:15
    restart: always    
    env_file: ../db/.env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ../db/postgresql.conf:/etc/postgresql/postgresql.conf
    labels:
      - "promtail=true"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf",
               "-c", "hba_file=/etc/postgresql/pg_hba.conf",]
    ports:
      - "5432:5432"

volumes:
  postgres_data: