name: Build and deploy SvelteKit web app to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Build and push docker image
        uses: ./.github/actions/build_and_push_docker_image
        with:
          service: web
          dockerfile_dir: apps/sveltastic
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_cr_username: ${{ secrets.GH_CR_USERNAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        uses: ./.github/actions/deploy_to_vps
        with:
          service: web
          vps_host: ${{ secrets.VPS_HOST }}
          vps_username: ${{ secrets.VPS_USERNAME }}
          vps_key: ${{ secrets.VPS_KEY }}
          vps_port: ${{ secrets.VPS_PORT }}
          vps_folder: ${{ secrets.VPS_FOLDER }}