name: Build and deploy SvelteKit web app to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy_web:
    uses: ./.github/workflows/deploy.yml
    with:
      service: web
      dockerfile_dir: apps/sveltastic
    secrets:
      GH_CR_USERNAME: ${{ secrets.GH_CR_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_KEY: ${{ secrets.VPS_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      VPS_FOLDER: ${{ secrets.VPS_FOLDER }}