on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
        description: The service to deploy
      dockerfile_dir:
        required: true
        type: string
        description: The directory containing the Dockerfile
    secrets:
      GH_CR_USERNAME:
        required: true
        description: The GitHub Container Registry username
      GITHUB_TOKEN:
        required: true
        description: The GitHub Container Registry password
      VPS_HOST:
        required: true
        description: The VPS host
      VPS_USERNAME:
        required: true
        description: The VPS username
      VPS_KEY:
        required: true
        description: The VPS key
      VPS_PORT:
        required: true
        description: The VPS port
      VPS_FOLDER:
        required: true
        description: The VPS folder
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_CR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/kapobajza/zdnevnik_${{ inputs.service }}:prod
          file: ${{ inputs.dockerfile_dir }}/Dockerfile
          target: prod
          platforms: linux/amd64
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/${{ secrets.VPS_FOLDER }}
            ./scripts/deploy.sh ${{ inputs.service }}