name: Build and deploy API to VPS

on:
  push:
    branches:
      - main
    paths:
      - 'apps/api/**/**.ts'
      - 'apps/api/package.json'
      - '!apps/api/README.md'

jobs:
  deploy_api:
    uses: ./.github/workflows/deploy.yml
    with:
      service: api
      dockerfile_dir: apps/api
    secrets:
      GH_CR_USERNAME: ${{ secrets.GH_CR_USERNAME }}
      GH_CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
      VPS_KEY: ${{ secrets.VPS_KEY }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      VPS_FOLDER: ${{ secrets.VPS_FOLDER }}